<h1>ch01_HomeWork_0</h1>

In [1]:
import numpy as np
n3= 3 

np.random.seed(0) 

A3= np.random.randint(-5,5,size=(n3,n3)) 

 
np.random.seed(1) 

b3= np.random.randint(-5,5,size=(n3,1)) 
 
x3= np.linalg.solve(A3, b3) 

checks= A3@x3 == b3
check=True
for i in checks:
    check&i

print( 

f''' 

n= {n3},  

A= {A3} 

b= {b3} 

x= {x3}

check= {check}

''') 

 

n= 3,  

A= [[ 0 -5 -2]
 [-2  2  4]
 [-2  0 -3]] 

b= [[0]
 [3]
 [4]] 

x= [[-1.75806452]
 [ 0.06451613]
 [-0.16129032]]

check= True




In [2]:
n5= 5 

np.random.seed(2) 

A5= np.random.randint(-5,5,size=(n5,n5)) 

 
np.random.seed(3) 

b5= np.random.randint(-5,5,size=(n5,1)) 
 
x5= np.linalg.solve(A5, b5) 

checks= A5@x5 == b5
check=True
for i in checks:
    check&i

print( 

f''' 

n= {n5},  

A= {A5} 

b= {b5} 

x= {x5} 

check= {check}

''') 

 

n= 5,  

A= [[ 3  3  1 -3  3]
 [ 2 -3 -4  0 -1]
 [-1  0  2 -2  1]
 [-1 -2  2  1 -4]
 [-2  0  3 -1  1]] 

b= [[ 3]
 [ 4]
 [-2]
 [ 3]
 [ 3]] 

x= [[ 6.13235294]
 [-6.04411765]
 [ 5.38235294]
 [ 5.75      ]
 [ 4.86764706]] 

check= True




In [3]:
n10= 10 

np.random.seed(4) 

A10= np.random.randint(-5,5,size=(n10,n10)) 

 
np.random.seed(5) 

b10= np.random.randint(-5,5,size=(n10,1)) 
 
x10= np.linalg.solve(A10, b10) 
 
checks= A10@x10 == b10
check=True
for i in checks:
    check&i

print( 

f''' 

n= {n10},  

A= {A10} 

b= {b10} 

x= {x10} 

check= {check}

''')  

 

n= 10,  

A= [[ 2  0 -4  3  2  3 -3  4  2  2]
 [ 2  4  3 -1 -3  1 -1 -2 -5  2]
 [ 0  0  4  1  1  3 -3  0  3 -4]
 [-3  2 -5  3 -2 -4 -5 -2 -3 -2]
 [-3  4 -3 -4 -5 -4  4  4 -5  2]
 [-3  1 -2  2  3 -3  1  2  2  4]
 [-3  2  0 -2 -5  0 -1 -2  3  4]
 [ 0  3  1  2 -5 -1  1  3 -1  3]
 [-4  4  0 -1 -3 -2 -1  2  1  1]
 [ 3 -5 -2  0  1 -4 -4  1 -5  3]] 

b= [[-2]
 [ 1]
 [ 1]
 [-5]
 [ 4]
 [ 3]
 [-1]
 [ 2]
 [-5]
 [-5]] 

x= [[-9.6889042 ]
 [-5.29476511]
 [ 1.56114311]
 [ 3.41077623]
 [-0.13824567]
 [ 7.77140026]
 [ 1.572224  ]
 [ 0.81234271]
 [-6.21076344]
 [ 2.12058537]] 

check= True




<h1>Matrix decompositions</h1>

In [4]:
n= 4  

 

np.random.seed(0) 

A= np.random.randint(-5,5,size=(n,n)) 

print(f'A= \n{A}') 

 

det= np.linalg.det(A) 

print(f'det= {det}') 

 

def ryDet(A): 

     

    n= A.shape[0] 

    if n>1: 

        i= 0 

        Bi=  np.delete(A, i, axis=0) 

        #print(f'\ni= {i}, Bi= \n{Bi}') 

         

        det= 0 

        for j in range(n): 

             

            Bij= np.delete(Bi,j, axis=1) 

            print(f'\ni,j= {i}{j}, Bij= \n{Bij}') 

             

            Dij= ryDet(Bij) #np.linalg.det(Bij) 

            print(f'.... Dij= {Dij}') 

             

            Cij= A[i,j]*Dij*(-1)**(i+j) 

            det += Cij 

        #print(f'det= {det}') 

        return det 

     

    elif A.shape[0]==1: 

        det= A[0,0] 

        return det 

    else: 

        return None 

 

det= ryDet(A) 

print(f'\ndet= {det}') 

A= 
[[ 0 -5 -2 -2]
 [ 2  4 -2  0]
 [-3 -1  2  1]
 [ 3  3 -4  1]]
det= -63.99999999999998

i,j= 00, Bij= 
[[ 4 -2  0]
 [-1  2  1]
 [ 3 -4  1]]

i,j= 00, Bij= 
[[ 2  1]
 [-4  1]]

i,j= 00, Bij= 
[[1]]
.... Dij= 1

i,j= 01, Bij= 
[[-4]]
.... Dij= -4
.... Dij= 6

i,j= 01, Bij= 
[[-1  1]
 [ 3  1]]

i,j= 00, Bij= 
[[1]]
.... Dij= 1

i,j= 01, Bij= 
[[3]]
.... Dij= 3
.... Dij= -4

i,j= 02, Bij= 
[[-1  2]
 [ 3 -4]]

i,j= 00, Bij= 
[[-4]]
.... Dij= -4

i,j= 01, Bij= 
[[3]]
.... Dij= 3
.... Dij= -2
.... Dij= 16

i,j= 01, Bij= 
[[ 2 -2  0]
 [-3  2  1]
 [ 3 -4  1]]

i,j= 00, Bij= 
[[ 2  1]
 [-4  1]]

i,j= 00, Bij= 
[[1]]
.... Dij= 1

i,j= 01, Bij= 
[[-4]]
.... Dij= -4
.... Dij= 6

i,j= 01, Bij= 
[[-3  1]
 [ 3  1]]

i,j= 00, Bij= 
[[1]]
.... Dij= 1

i,j= 01, Bij= 
[[3]]
.... Dij= 3
.... Dij= -6

i,j= 02, Bij= 
[[-3  2]
 [ 3 -4]]

i,j= 00, Bij= 
[[-4]]
.... Dij= -4

i,j= 01, Bij= 
[[3]]
.... Dij= 3
.... Dij= 6
.... Dij= 0

i,j= 02, Bij= 
[[ 2  4  0]
 [-3 -1  1]
 [ 3  3  1]]

i,j= 00, Bij= 
[[-1  1]
 

<h1>ch01_HomeWork_1 </h1><br>
參考<a https://people.duke.edu/~ccc14/sta-663-2016/07_LinearAlgebra2.html>This</a> <br>
並跑程式碼

In [5]:
import os
import sys
import glob
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline
%precision 4
plt.style.use('ggplot')

In [6]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,3,4],[2,1,3],[4,1,2]])

L = np.array([[1,0,0],[2,1,0],[4,11/5,1]])
U = np.array([[1,3,4],[0,-5,-5],[0,0,-3]])
print(L.dot(U))
print(L)
print(U)

[[1. 3. 4.]
 [2. 1. 3.]
 [4. 1. 2.]]
[[1.  0.  0. ]
 [2.  1.  0. ]
 [4.  2.2 1. ]]
[[ 1  3  4]
 [ 0 -5 -5]
 [ 0  0 -3]]


In [7]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,3,4],[2,1,3],[4,1,2]])

print(A)

P, L, U = la.lu(A)
print(np.dot(P.T, A))
print
print(np.dot(L, U))
print(P)
print(L)
print(U)

[[1 3 4]
 [2 1 3]
 [4 1 2]]
[[4. 1. 2.]
 [1. 3. 4.]
 [2. 1. 3.]]
[[4. 1. 2.]
 [1. 3. 4.]
 [2. 1. 3.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.     0.     0.    ]
 [0.25   1.     0.    ]
 [0.5    0.1818 1.    ]]
[[4.     1.     2.    ]
 [0.     2.75   3.5   ]
 [0.     0.     1.3636]]


In [8]:
A = np.array([[1,3,5],[3,13,23],[5,23,42]])
L = la.cholesky(A)
print(np.dot(L.T, L))

print(L)
print(A)

[[ 1.  3.  5.]
 [ 3. 13. 23.]
 [ 5. 23. 42.]]
[[1. 3. 5.]
 [0. 2. 4.]
 [0. 0. 1.]]
[[ 1  3  5]
 [ 3 13 23]
 [ 5 23 42]]


In [9]:
A = np.array([[0,1,1],[2,1,0],[3,4,5]])

u, V = la.eig(A)
print(np.dot(V,np.dot(np.diag(u), la.inv(V))))
print(u)

[[ 0.+0.j  1.+0.j  1.+0.j]
 [ 2.+0.j  1.+0.j -0.+0.j]
 [ 3.+0.j  4.+0.j  5.+0.j]]
[ 5.8541+0.j -0.8541+0.j  1.    +0.j]


In [10]:
A = np.array([[0,1],[-1,0]])
print(A)

u, V = la.eig(A)
print(np.dot(V,np.dot(np.diag(u), la.inv(V))))
print(u)

[[ 0  1]
 [-1  0]]
[[ 0.+0.j  1.+0.j]
 [-1.+0.j  0.+0.j]]
[0.+1.j 0.-1.j]


In [11]:
A = np.array([[0,1,1],[2,1,0],[3,4,5]])
u, V = la.eig(A)
print(u)
print(np.real_if_close(u))

[ 5.8541+0.j -0.8541+0.j  1.    +0.j]
[ 5.8541 -0.8541  1.    ]


In [12]:
A = np.array([[8,6,4,1],[1,4,5,1],[8,4,1,1],[1,4,3,6]])
b = np.array([19,11,14,14])
la.solve(A,b)

array([1., 1., 1., 1.])

In [13]:
b = np.array([19.01,11.05,14.07,14.05])
la.solve(A,b)

array([-2.34 ,  9.745, -4.85 , -1.34 ])

In [14]:
U, s, V = np.linalg.svd(A)
print(s)
print(max(s)/min(s))

[15.5457  6.9002  3.8363  0.0049]
3198.6725811997335


In [15]:
A = np.array([[1,2,3],[2,-4,6],[3,-9,-3]])
L = np.array([[1,0,0],[2,1,0],[3,15/8,1]])
U = np.array([[1,2,3],[0,-8,0],[0,0,-6]])
print(L.dot(U))
print(L)
print(U)

[[ 1.  2.  3.]
 [ 2. -4.  6.]
 [ 3. -9.  3.]]
[[1.    0.    0.   ]
 [2.    1.    0.   ]
 [3.    1.875 1.   ]]
[[ 1  2  3]
 [ 0 -8  0]
 [ 0  0 -6]]


In [16]:
A = np.array([[1,2,3],[2,-4,6],[3,6,-3]]) #A為非正定

def svdsolver(A,b):
    U, s, V = np.linalg.svd(A)
    if np.prod(s) == 0:
       print("Matrix is singular")
    else:
       return np.dot(np.dot((V.T).dot(np.diag(s**(-1))), U.T),b)

In [17]:
A = np.array([[1,1],[1,2]])
b = np.array([3,1])
print(np.linalg.solve(A,b))
print(svdsolver(A,b))

[ 5. -2.]
[ 5. -2.]
