In [1]:
import scipy.stats as st 
import scipy.special as sc
import numpy as np
import sympy as sm
 

percent_points= 百分位= [0, 1/4, 2/4, 3/4, 1] 
 

# Bernoulli 
k= [0,1] 
 

X=   st.bernoulli(p= 0.2).rvs(size= 10) 
pmf= st.bernoulli(p= 0.2).pmf(k) 
cdf= st.bernoulli(p= 0.2).cdf(k) 
ppf= st.bernoulli(p= 0.2).ppf(percent_points) 
X, pmf, cdf, ppf

(array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0]),
 array([0.8, 0.2]),
 array([0.8, 1. ]),
 array([-1.,  0.,  0.,  0.,  1.]))

In [2]:
# Discrete Uniform (randint) 
k=   np.arange(0,11) 
 

X=   st.randint(low=0, high=10).rvs(size= 10) 
pmf= st.randint(low=0, high=10).pmf(k) 
cdf= st.randint(low=0, high=10).cdf(k) 
ppf= st.randint(low=0, high=10).ppf(percent_points) 
X, pmf, cdf, ppf

(array([4, 7, 8, 2, 9, 1, 2, 5, 6, 8]),
 array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0. ]),
 array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1. ]),
 array([-1.,  2.,  4.,  7.,  9.]))

In [3]:
# Binomial 
k=   np.arange(0,11) 
 

X=   st.binom(n=10, p= 0.2).rvs(size= 10) 
pmf= st.binom(n=10, p= 0.2).pmf(k) 
cdf= st.binom(n=10, p= 0.2).cdf(k) 
ppf= st.binom(n=10, p= 0.2).ppf(percent_points) 
X, pmf, cdf, ppf

(array([1, 1, 1, 5, 3, 4, 1, 3, 0, 1]),
 array([1.07374182e-01, 2.68435456e-01, 3.01989888e-01, 2.01326592e-01,
        8.80803840e-02, 2.64241152e-02, 5.50502400e-03, 7.86432000e-04,
        7.37280000e-05, 4.09600000e-06, 1.02400000e-07]),
 array([0.10737418, 0.37580964, 0.67779953, 0.87912612, 0.9672065 ,
        0.99363062, 0.99913564, 0.99992207, 0.9999958 , 0.9999999 ,
        1.        ]),
 array([-1.,  1.,  2.,  3., 10.]))

In [4]:
n=  10 
vb= [sm.binomial(n,k) for k in range(n+1)] 
vb 

[1, 10, 45, 120, 210, 252, 210, 120, 45, 10, 1]

In [5]:
# Poisson 
k=   np.arange(0,11) 
X=   st.poisson(mu=2).rvs(size= 10) 
pmf= st.poisson(mu=2).pmf(k) 
cdf= st.poisson(mu=2).cdf(k) 
ppf= st.poisson(mu=2).ppf(percent_points) 
X, pmf, cdf, ppf

(array([0, 3, 3, 1, 2, 2, 1, 2, 0, 2]),
 array([1.35335283e-01, 2.70670566e-01, 2.70670566e-01, 1.80447044e-01,
        9.02235222e-02, 3.60894089e-02, 1.20298030e-02, 3.43708656e-03,
        8.59271640e-04, 1.90949253e-04, 3.81898506e-05]),
 array([0.13533528, 0.40600585, 0.67667642, 0.85712346, 0.94734698,
        0.98343639, 0.99546619, 0.99890328, 0.99976255, 0.9999535 ,
        0.99999169]),
 array([-1.,  1.,  2.,  3., inf]))

In [6]:
# Geometric 
k=   np.arange(0,21) 
X=   st.geom(p=.2).rvs(size= 10) 
pmf= st.geom(p=.2).pmf(k) 
cdf= st.geom(p=.2).cdf(k) 
ppf= st.geom(p=.2).ppf(percent_points) 
X, pmf, cdf, ppf

(array([ 8,  8,  1,  1,  1,  4,  6,  2, 20,  1]),
 array([0.        , 0.2       , 0.16      , 0.128     , 0.1024    ,
        0.08192   , 0.065536  , 0.0524288 , 0.04194304, 0.03355443,
        0.02684355, 0.02147484, 0.01717987, 0.0137439 , 0.01099512,
        0.00879609, 0.00703687, 0.0056295 , 0.0045036 , 0.00360288,
        0.0028823 ]),
 array([0.        , 0.2       , 0.36      , 0.488     , 0.5904    ,
        0.67232   , 0.737856  , 0.7902848 , 0.83222784, 0.86578227,
        0.89262582, 0.91410065, 0.93128052, 0.94502442, 0.95601953,
        0.96481563, 0.9718525 , 0.977482  , 0.9819856 , 0.98558848,
        0.98847078]),
 array([ 0.,  2.,  4.,  7., inf]))

In [7]:
# Negative Binomial 
 

k=   np.arange(0,21) 
X=   st.nbinom(n=10, p= 0.2).rvs(size= 10) 
pmf= st.nbinom(n=10, p= 0.2).pmf(k) 
cdf= st.nbinom(n=10, p= 0.2).cdf(k) 
ppf= st.nbinom(n=10, p= 0.2).ppf(percent_points) 
X, pmf, cdf, ppf 

(array([18, 30, 61, 39, 34, 29, 22, 37, 51, 40]),
 array([1.02400000e-07, 8.19200000e-07, 3.60448000e-06, 1.15343360e-05,
        2.99892736e-05, 6.71759729e-05, 1.34351946e-04, 2.45672129e-04,
        4.17642620e-04, 6.68228192e-04, 1.01570685e-03, 1.47739178e-03,
        2.06834850e-03, 2.80022566e-03, 3.68029658e-03, 4.71077962e-03,
        5.88847453e-03, 7.20472177e-03, 8.64566613e-03, 1.01927853e-02,
        1.18236310e-02]),
 array([1.02400000e-07, 9.21600000e-07, 4.52608000e-06, 1.60604160e-05,
        4.60496896e-05, 1.13225662e-04, 2.47577608e-04, 4.93249738e-04,
        9.10892357e-04, 1.57912055e-03, 2.59482740e-03, 4.07221918e-03,
        6.14056768e-03, 8.94079334e-03, 1.26210899e-02, 1.73318695e-02,
        2.32203441e-02, 3.04250658e-02, 3.90707320e-02, 4.92635173e-02,
        6.10871483e-02]),
 array([-1., 30., 39., 49., inf]))

In [8]:
vnb= [(k, sm.binomial(-n,k)) for k in range(n+1)] 
vnb

[(0, 1),
 (1, -10),
 (2, 55),
 (3, -220),
 (4, 715),
 (5, -2002),
 (6, 5005),
 (7, -11440),
 (8, 24310),
 (9, -48620),
 (10, 92378)]

In [9]:
x, μ= sm.symbols('x, μ') 
σ=    sm.symbols('σ', positive=True)
f= (1+x)**(-n)
f

(x + 1)**(-10)

In [10]:
f.expand()

1/(x**10 + 10*x**9 + 45*x**8 + 120*x**7 + 210*x**6 + 252*x**5 + 210*x**4 + 120*x**3 + 45*x**2 + 10*x + 1)

In [11]:
# Normal (Gauss) distribution 
π= sm.pi

def f(x): 
    y= sm.exp(-x**2 /2) / sm.sqrt(2*π) 
    return y 
 

def F(x): 
    t= sm.symbols('t') 
    y= f(t).integrate((t, -sm.oo, x)) 
    return y 
 

x= sm.symbols('x') 
f(x), F(x) 

(sqrt(2)*exp(-x**2/2)/(2*sqrt(pi)), erf(sqrt(2)*x/2)/2 + 1/2)

In [12]:
def ϕ(x): 
    y= sm.exp(-(x**2)/2) /sm.sqrt(2*π) 
    return y 
 

def f(x, μ=0, σ=1): 
    y= ϕ((x-μ)/σ) / σ 
    return y 


In [13]:
E_X= ( 
    (x*f(x,μ,σ)) 
    .integrate( 
        (x,-sm.oo,sm.oo)) 
).simplify() 
 

# E[X**2]= 
E_XX= ( 
    ((x**2)*f(x,μ,σ)) 
    .integrate( 
        (x,-sm.oo,sm.oo)) 
).simplify() 
 

# Var[X]= 
Var_X= ( 
    (((x-μ)**2)*f(x,μ,σ)) 
    .integrate( 
        (x,-sm.oo,sm.oo)) 
).simplify() 
 

# Mode[X]=  
Mode_X= ( 
    sm.solve( 
        f(x,μ,σ).diff(x), 
        x) 
) 
 

display(E_X) 
display(E_XX) 
display(Var_X) 
display(Mode_X) 

μ

μ**2 + σ**2

σ**2

[μ]